const MovieList = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction", 
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Matrix",
    "Goodfellas",
    "The Lord of the Rings: The Return of the King",
    "Interstellar",
    "The Empire Strikes Back",
    "The Green Mile",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "Parasite",
    "The Lion King",
    "Whiplash",
    "The Prestige",
    "Gladiator",
    "The Departed",
    "Back to the Future",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Joker",
    "Schindler's List",
    "Avengers: Endgame",
    "The Truman Show",
    "Se7en",
    "Django Unchained",
    "The Grand Budapest Hotel",
    "The Social Network",
    "La La Land",
    "The Revenant",
    "The Imitation Game",
    "A Beautiful Mind",
    "Braveheart",
    "Titanic",
    "The Great Gatsby",
    "No Country for Old Men",
    "The Big Lebowski",
    "Inglourious Basterds",
    "Blade Runner 2049",
    "Mad Max: Fury Road",
    "The Irishman",
    "Jojo Rabbit",
    "Moonlight",
    "Birdman",
    "Life of Pi",
    "Slumdog Millionaire",
    "12 Years a Slave",
    "Her",
    "Ex Machina",
    "Arrival",
    "Shutter Island",
    "Prisoners",
    "Gone Girl",
    "Black Swan",
    "The Wolf of Wall Street",
    "Bohemian Rhapsody",
    "Rocketman",
    "Into the Wild",
    "The Curious Case of Benjamin Button",
    "Cast Away",
    "Catch Me If You Can",
    "The Pursuit of Happyness",
    "Dallas Buyers Club",
    "The Theory of Everything",
    "The King’s Speech",
    "Spotlight",
    "The Shape of Water",
    "Marriage Story",
    "Nomadland",
    "Don't Look Up",
    "Knives Out",
    "The Batman",
    "Dune",
    "Everything Everywhere All At Once",
    "The Whale",
    "The Fabelmans",
    "Tár",
    "Top Gun: Maverick",
    "RRR",
    "Avatar: The Way of Water",
    "Oppenheimer",
    "Barbie",
    "Killers of the Flower Moon",
    "Poor Things",
    "The Holdovers",
    "Past Lives",
    "Anatomy of a Fall",
    "Maestro",
    "American Fiction",
    "Napoleon",
    "The Marvels",
    "Asteroid City",
    "The Banshees of Inisherin",
    "Triangle of Sadness",
    "Elvis",
    "The Menu",
    "Don't Worry Darling",
    "Nope",
    "Glass Onion",
    "The Last Duel",
  ];

  export default MovieList;